/*****************************************************************************
*
*  PROJECT:     Lua Interpreter
*  LICENSE:     See LICENSE in the top level directory
*  FILE:        glDriver/gl_lua.cpp
*  PURPOSE:     OpenGL driver for MTA:Lua
*  DEVELOPERS:  Martin Turski <quiret@gmx.de>
*
*  Multi Theft Auto is available from http://www.multitheftauto.com/
*
*****************************************************************************/

#include <StdInc.h>

static LUA_DECLARE( create )
{
    Win32Dialog *dlg;

    LUA_ARGS_BEGIN;
    argStream.ReadClass( dlg, LUACLASS_WIN32DIALOG );
    LUA_ARGS_END;

    glDriver *driver = new glDriver( L, dlg );
    driver->PushStack( L );
    return 1;
}

static LUA_DECLARE( getParamNames )
{
    lua_createtable( L, 234, 0 );
    lua_pushlstring( L, "GL_ACCUM_ALPHA_BITS", 19 );
    lua_rawseti( L, -2, 1 );
    lua_pushlstring( L, "GL_ACCUM_BLUE_BITS", 18 );
    lua_rawseti( L, -2, 2 );
    lua_pushlstring( L, "GL_ACCUM_CLEAR_VALUE", 20 );
    lua_rawseti( L, -2, 3 );
    lua_pushlstring( L, "GL_ACCUM_GREEN_BITS", 19 );
    lua_rawseti( L, -2, 4 );
    lua_pushlstring( L, "GL_ACCUM_RED_BITS", 17 );
    lua_rawseti( L, -2, 5 );
    lua_pushlstring( L, "GL_ALPHA_BIAS", 13 );
    lua_rawseti( L, -2, 6 );
    lua_pushlstring( L, "GL_ALPHA_BITS", 13 );
    lua_rawseti( L, -2, 7 );
    lua_pushlstring( L, "GL_ALPHA_SCALE", 14 );
    lua_rawseti( L, -2, 8 );
    lua_pushlstring( L, "GL_ALPHA_TEST", 13 );
    lua_rawseti( L, -2, 9 );
    lua_pushlstring( L, "GL_ALPHA_TEST_FUNC", 18 );
    lua_rawseti( L, -2, 10 );
    lua_pushlstring( L, "GL_ALPHA_TEST_REF", 17 );
    lua_rawseti( L, -2, 11 );
    lua_pushlstring( L, "GL_ATTRIB_STACK_DEPTH", 21 );
    lua_rawseti( L, -2, 12 );
    lua_pushlstring( L, "GL_AUTO_NORMAL", 14 );
    lua_rawseti( L, -2, 13 );
    lua_pushlstring( L, "GL_AUX_BUFFERS", 14 );
    lua_rawseti( L, -2, 14 );
    lua_pushlstring( L, "GL_BLEND", 8 );
    lua_rawseti( L, -2, 15 );
    lua_pushlstring( L, "GL_BLEND_DST", 12 );
    lua_rawseti( L, -2, 16 );
    lua_pushlstring( L, "GL_BLEND_SRC", 12 );
    lua_rawseti( L, -2, 17 );
    lua_pushlstring( L, "GL_BLUE_BIAS", 12 );
    lua_rawseti( L, -2, 18 );
    lua_pushlstring( L, "GL_BLUE_BITS", 12 );
    lua_rawseti( L, -2, 19 );
    lua_pushlstring( L, "GL_BLUE_SCALE", 13 );
    lua_rawseti( L, -2, 20 );
    lua_pushlstring( L, "GL_CLIENT_ATTRIB_STACK_DEPTH", 28 );
    lua_rawseti( L, -2, 21 );
    lua_pushlstring( L, "GL_CLIP_PLANE0", 14 );
    lua_rawseti( L, -2, 22 );
    lua_pushlstring( L, "GL_CLIP_PLANE1", 14 );
    lua_rawseti( L, -2, 23 );
    lua_pushlstring( L, "GL_CLIP_PLANE2", 14 );
    lua_rawseti( L, -2, 24 );
    lua_pushlstring( L, "GL_CLIP_PLANE3", 14 );
    lua_rawseti( L, -2, 25 );
    lua_pushlstring( L, "GL_CLIP_PLANE4", 14 );
    lua_rawseti( L, -2, 26 );
    lua_pushlstring( L, "GL_CLIP_PLANE5", 14 );
    lua_rawseti( L, -2, 27 );
    lua_pushlstring( L, "GL_COLOR_ARRAY", 14 );
    lua_rawseti( L, -2, 28 );
    lua_pushlstring( L, "GL_COLOR_ARRAY_SIZE", 19 );
    lua_rawseti( L, -2, 29 );
    lua_pushlstring( L, "GL_COLOR_ARRAY_STRIDE", 21 );
    lua_rawseti( L, -2, 30 );
    lua_pushlstring( L, "GL_COLOR_ARRAY_TYPE", 19 );
    lua_rawseti( L, -2, 31 );
    lua_pushlstring( L, "GL_COLOR_CLEAR_VALUE", 20 );
    lua_rawseti( L, -2, 32 );
    lua_pushlstring( L, "GL_COLOR_LOGIC_OP", 17 );
    lua_rawseti( L, -2, 33 );
    lua_pushlstring( L, "GL_COLOR_MATERIAL", 17 );
    lua_rawseti( L, -2, 34 );
    lua_pushlstring( L, "GL_COLOR_MATERIAL_FACE", 22 );
    lua_rawseti( L, -2, 35 );
    lua_pushlstring( L, "GL_COLOR_MATERIAL_PARAMETER", 27 );
    lua_rawseti( L, -2, 36 );
    lua_pushlstring( L, "GL_COLOR_WRITEMASK", 18 );
    lua_rawseti( L, -2, 37 );
    lua_pushlstring( L, "GL_CULL_FACE", 12 );
    lua_rawseti( L, -2, 38 );
    lua_pushlstring( L, "GL_CULL_FACE_MODE", 17 );
    lua_rawseti( L, -2, 39 );
    lua_pushlstring( L, "GL_CURRENT_COLOR", 16 );
    lua_rawseti( L, -2, 40 );
    lua_pushlstring( L, "GL_CURRENT_INDEX", 16 );
    lua_rawseti( L, -2, 41 );
    lua_pushlstring( L, "GL_CURRENT_NORMAL", 17 );
    lua_rawseti( L, -2, 42 );
    lua_pushlstring( L, "GL_CURRENT_RASTER_COLOR", 23 );
    lua_rawseti( L, -2, 43 );
    lua_pushlstring( L, "GL_CURRENT_RASTER_DISTANCE", 26 );
    lua_rawseti( L, -2, 44 );
    lua_pushlstring( L, "GL_CURRENT_RASTER_INDEX", 23 );
    lua_rawseti( L, -2, 45 );
    lua_pushlstring( L, "GL_CURRENT_RASTER_POSITION", 26 );
    lua_rawseti( L, -2, 46 );
    lua_pushlstring( L, "GL_CURRENT_RASTER_POSITION_VALID", 32 );
    lua_rawseti( L, -2, 47 );
    lua_pushlstring( L, "GL_CURRENT_RASTER_TEXTURE_COORDS", 32 );
    lua_rawseti( L, -2, 48 );
    lua_pushlstring( L, "GL_CURRENT_TEXTURE_COORDS", 25 );
    lua_rawseti( L, -2, 49 );
    lua_pushlstring( L, "GL_DEPTH_BIAS", 13 );
    lua_rawseti( L, -2, 50 );
    lua_pushlstring( L, "GL_DEPTH_BITS", 13 );
    lua_rawseti( L, -2, 51 );
    lua_pushlstring( L, "GL_DEPTH_CLEAR_VALUE", 20 );
    lua_rawseti( L, -2, 52 );
    lua_pushlstring( L, "GL_DEPTH_FUNC", 13 );
    lua_rawseti( L, -2, 53 );
    lua_pushlstring( L, "GL_DEPTH_RANGE", 14 );
    lua_rawseti( L, -2, 54 );
    lua_pushlstring( L, "GL_DEPTH_SCALE", 14 );
    lua_rawseti( L, -2, 55 );
    lua_pushlstring( L, "GL_DEPTH_TEST", 13 );
    lua_rawseti( L, -2, 56 );
    lua_pushlstring( L, "GL_DEPTH_WRITEMASK", 18 );
    lua_rawseti( L, -2, 57 );
    lua_pushlstring( L, "GL_DITHER", 9 );
    lua_rawseti( L, -2, 58 );
    lua_pushlstring( L, "GL_DOUBLEBUFFER", 15 );
    lua_rawseti( L, -2, 59 );
    lua_pushlstring( L, "GL_DRAW_BUFFER", 14 );
    lua_rawseti( L, -2, 60 );
    lua_pushlstring( L, "GL_EDGE_FLAG", 12 );
    lua_rawseti( L, -2, 61 );
    lua_pushlstring( L, "GL_EDGE_FLAG_ARRAY", 18 );
    lua_rawseti( L, -2, 62 );
    lua_pushlstring( L, "GL_EDGE_FLAG_ARRAY_STRIDE", 25 );
    lua_rawseti( L, -2, 63 );
    lua_pushlstring( L, "GL_FOG", 6 );
    lua_rawseti( L, -2, 64 );
    lua_pushlstring( L, "GL_FOG_COLOR", 12 );
    lua_rawseti( L, -2, 65 );
    lua_pushlstring( L, "GL_FOG_DENSITY", 14 );
    lua_rawseti( L, -2, 66 );
    lua_pushlstring( L, "GL_FOG_END", 10 );
    lua_rawseti( L, -2, 67 );
    lua_pushlstring( L, "GL_FOG_HINT", 11 );
    lua_rawseti( L, -2, 68 );
    lua_pushlstring( L, "GL_FOG_INDEX", 12 );
    lua_rawseti( L, -2, 69 );
    lua_pushlstring( L, "GL_FOG_MODE", 11 );
    lua_rawseti( L, -2, 70 );
    lua_pushlstring( L, "GL_FOG_START", 12 );
    lua_rawseti( L, -2, 71 );
    lua_pushlstring( L, "GL_FRONT_FACE", 13 );
    lua_rawseti( L, -2, 72 );
    lua_pushlstring( L, "GL_GREEN_BIAS", 13 );
    lua_rawseti( L, -2, 73 );
    lua_pushlstring( L, "GL_GREEN_BITS", 13 );
    lua_rawseti( L, -2, 74 );
    lua_pushlstring( L, "GL_GREEN_SCALE", 14 );
    lua_rawseti( L, -2, 75 );
    lua_pushlstring( L, "GL_INDEX_ARRAY", 14 );
    lua_rawseti( L, -2, 76 );
    lua_pushlstring( L, "GL_INDEX_ARRAY_STRIDE", 21 );
    lua_rawseti( L, -2, 77 );
    lua_pushlstring( L, "GL_INDEX_ARRAY_TYPE", 19 );
    lua_rawseti( L, -2, 78 );
    lua_pushlstring( L, "GL_INDEX_BITS", 13 );
    lua_rawseti( L, -2, 79 );
    lua_pushlstring( L, "GL_INDEX_CLEAR_VALUE", 20 );
    lua_rawseti( L, -2, 80 );
    lua_pushlstring( L, "GL_INDEX_LOGIC_OP", 17 );
    lua_rawseti( L, -2, 81 );
    lua_pushlstring( L, "GL_INDEX_MODE", 13 );
    lua_rawseti( L, -2, 82 );
    lua_pushlstring( L, "GL_INDEX_OFFSET", 15 );
    lua_rawseti( L, -2, 83 );
    lua_pushlstring( L, "GL_INDEX_SHIFT", 14 );
    lua_rawseti( L, -2, 84 );
    lua_pushlstring( L, "GL_INDEX_WRITEMASK", 18 );
    lua_rawseti( L, -2, 85 );
    lua_pushlstring( L, "GL_LIGHT0", 9 );
    lua_rawseti( L, -2, 86 );
    lua_pushlstring( L, "GL_LIGHT1", 9 );
    lua_rawseti( L, -2, 87 );
    lua_pushlstring( L, "GL_LIGHT2", 9 );
    lua_rawseti( L, -2, 88 );
    lua_pushlstring( L, "GL_LIGHT3", 9 );
    lua_rawseti( L, -2, 89 );
    lua_pushlstring( L, "GL_LIGHT4", 9 );
    lua_rawseti( L, -2, 90 );
    lua_pushlstring( L, "GL_LIGHT5", 9 );
    lua_rawseti( L, -2, 91 );
    lua_pushlstring( L, "GL_LIGHT6", 9 );
    lua_rawseti( L, -2, 92 );
    lua_pushlstring( L, "GL_LIGHT7", 9 );
    lua_rawseti( L, -2, 93 );
    lua_pushlstring( L, "GL_LIGHTING", 11 );
    lua_rawseti( L, -2, 94 );
    lua_pushlstring( L, "GL_LIGHT_MODEL_AMBIENT", 22 );
    lua_rawseti( L, -2, 95 );
    lua_pushlstring( L, "GL_LIGHT_MODEL_LOCAL_VIEWER", 27 );
    lua_rawseti( L, -2, 96 );
    lua_pushlstring( L, "GL_LIGHT_MODEL_TWO_SIDE", 23 );
    lua_rawseti( L, -2, 97 );
    lua_pushlstring( L, "GL_LINE_SMOOTH", 14 );
    lua_rawseti( L, -2, 98 );
    lua_pushlstring( L, "GL_LINE_SMOOTH_HINT", 19 );
    lua_rawseti( L, -2, 99 );
    lua_pushlstring( L, "GL_LINE_STIPPLE", 15 );
    lua_rawseti( L, -2, 100 );
    lua_pushlstring( L, "GL_LINE_STIPPLE_PATTERN", 23 );
    lua_rawseti( L, -2, 101 );
    lua_pushlstring( L, "GL_LINE_STIPPLE_REPEAT", 22 );
    lua_rawseti( L, -2, 102 );
    lua_pushlstring( L, "GL_LINE_WIDTH", 13 );
    lua_rawseti( L, -2, 103 );
    lua_pushlstring( L, "GL_LINE_WIDTH_GRANULARITY", 25 );
    lua_rawseti( L, -2, 104 );
    lua_pushlstring( L, "GL_LINE_WIDTH_RANGE", 19 );
    lua_rawseti( L, -2, 105 );
    lua_pushlstring( L, "GL_LIST_BASE", 12 );
    lua_rawseti( L, -2, 106 );
    lua_pushlstring( L, "GL_LIST_INDEX", 13 );
    lua_rawseti( L, -2, 107 );
    lua_pushlstring( L, "GL_LIST_MODE", 12 );
    lua_rawseti( L, -2, 108 );
    lua_pushlstring( L, "GL_LOGIC_OP", 11 );
    lua_rawseti( L, -2, 109 );
    lua_pushlstring( L, "GL_LOGIC_OP_MODE", 16 );
    lua_rawseti( L, -2, 110 );
    lua_pushlstring( L, "GL_MAP1_COLOR_4", 15 );
    lua_rawseti( L, -2, 111 );
    lua_pushlstring( L, "GL_MAP1_GRID_DOMAIN", 19 );
    lua_rawseti( L, -2, 112 );
    lua_pushlstring( L, "GL_MAP1_GRID_SEGMENTS", 21 );
    lua_rawseti( L, -2, 113 );
    lua_pushlstring( L, "GL_MAP1_INDEX", 13 );
    lua_rawseti( L, -2, 114 );
    lua_pushlstring( L, "GL_MAP1_NORMAL", 14 );
    lua_rawseti( L, -2, 115 );
    lua_pushlstring( L, "GL_MAP1_TEXTURE_COORD_1", 23 );
    lua_rawseti( L, -2, 116 );
    lua_pushlstring( L, "GL_MAP1_TEXTURE_COORD_2", 23 );
    lua_rawseti( L, -2, 117 );
    lua_pushlstring( L, "GL_MAP1_TEXTURE_COORD_3", 23 );
    lua_rawseti( L, -2, 118 );
    lua_pushlstring( L, "GL_MAP1_TEXTURE_COORD_4", 23 );
    lua_rawseti( L, -2, 119 );
    lua_pushlstring( L, "GL_MAP1_VERTEX_3", 16 );
    lua_rawseti( L, -2, 120 );
    lua_pushlstring( L, "GL_MAP1_VERTEX_4", 16 );
    lua_rawseti( L, -2, 121 );
    lua_pushlstring( L, "GL_MAP2_COLOR_4", 15 );
    lua_rawseti( L, -2, 122 );
    lua_pushlstring( L, "GL_MAP2_GRID_DOMAIN", 19 );
    lua_rawseti( L, -2, 123 );
    lua_pushlstring( L, "GL_MAP2_GRID_SEGMENTS", 21 );
    lua_rawseti( L, -2, 124 );
    lua_pushlstring( L, "GL_MAP2_INDEX", 13 );
    lua_rawseti( L, -2, 125 );
    lua_pushlstring( L, "GL_MAP2_NORMAL", 14 );
    lua_rawseti( L, -2, 126 );
    lua_pushlstring( L, "GL_MAP2_TEXTURE_COORD_1", 23 );
    lua_rawseti( L, -2, 127 );
    lua_pushlstring( L, "GL_MAP2_TEXTURE_COORD_2", 23 );
    lua_rawseti( L, -2, 128 );
    lua_pushlstring( L, "GL_MAP2_TEXTURE_COORD_3", 23 );
    lua_rawseti( L, -2, 129 );
    lua_pushlstring( L, "GL_MAP2_TEXTURE_COORD_4", 23 );
    lua_rawseti( L, -2, 130 );
    lua_pushlstring( L, "GL_MAP2_VERTEX_3", 16 );
    lua_rawseti( L, -2, 131 );
    lua_pushlstring( L, "GL_MAP2_VERTEX_4", 16 );
    lua_rawseti( L, -2, 132 );
    lua_pushlstring( L, "GL_MAP_COLOR", 12 );
    lua_rawseti( L, -2, 133 );
    lua_pushlstring( L, "GL_MAP_STENCIL", 14 );
    lua_rawseti( L, -2, 134 );
    lua_pushlstring( L, "GL_MATRIX_MODE", 14 );
    lua_rawseti( L, -2, 135 );
    lua_pushlstring( L, "GL_MAX_CLIENT_ATTRIB_STACK_DEPTH", 32 );
    lua_rawseti( L, -2, 136 );
    lua_pushlstring( L, "GL_MAX_ATTRIB_STACK_DEPTH", 25 );
    lua_rawseti( L, -2, 137 );
    lua_pushlstring( L, "GL_MAX_CLIP_PLANES", 18 );
    lua_rawseti( L, -2, 138 );
    lua_pushlstring( L, "GL_MAX_EVAL_ORDER", 17 );
    lua_rawseti( L, -2, 139 );
    lua_pushlstring( L, "GL_MAX_LIGHTS", 13 );
    lua_rawseti( L, -2, 140 );
    lua_pushlstring( L, "GL_MAX_LIST_NESTING", 19 );
    lua_rawseti( L, -2, 141 );
    lua_pushlstring( L, "GL_MAX_MODELVIEW_STACK_DEPTH", 28 );
    lua_rawseti( L, -2, 142 );
    lua_pushlstring( L, "GL_MAX_NAME_STACK_DEPTH", 23 );
    lua_rawseti( L, -2, 143 );
    lua_pushlstring( L, "GL_MAX_PIXEL_MAP_TABLE", 22 );
    lua_rawseti( L, -2, 144 );
    lua_pushlstring( L, "GL_MAX_PROJECTION_STACK_DEPTH", 29 );
    lua_rawseti( L, -2, 145 );
    lua_pushlstring( L, "GL_MAX_TEXTURE_SIZE", 19 );
    lua_rawseti( L, -2, 146 );
    lua_pushlstring( L, "GL_MAX_TEXTURE_STACK_DEPTH", 26 );
    lua_rawseti( L, -2, 147 );
    lua_pushlstring( L, "GL_MAX_VIEWPORT_DIMS", 20 );
    lua_rawseti( L, -2, 148 );
    lua_pushlstring( L, "GL_MODELVIEW_MATRIX", 19 );
    lua_rawseti( L, -2, 149 );
    lua_pushlstring( L, "GL_MODELVIEW_STACK_DEPTH", 24 );
    lua_rawseti( L, -2, 150 );
    lua_pushlstring( L, "GL_NAME_STACK_DEPTH", 19 );
    lua_rawseti( L, -2, 151 );
    lua_pushlstring( L, "GL_NORMAL_ARRAY", 15 );
    lua_rawseti( L, -2, 152 );
    lua_pushlstring( L, "GL_NORMAL_ARRAY_STRIDE", 22 );
    lua_rawseti( L, -2, 153 );
    lua_pushlstring( L, "GL_NORMAL_ARRAY_TYPE", 20 );
    lua_rawseti( L, -2, 154 );
    lua_pushlstring( L, "GL_NORMALIZE", 12 );
    lua_rawseti( L, -2, 155 );
    lua_pushlstring( L, "GL_PACK_ALIGNMENT", 17 );
    lua_rawseti( L, -2, 156 );
    lua_pushlstring( L, "GL_PACK_LSB_FIRST", 17 );
    lua_rawseti( L, -2, 157 );
    lua_pushlstring( L, "GL_PACK_ROW_LENGTH", 18 );
    lua_rawseti( L, -2, 158 );
    lua_pushlstring( L, "GL_PACK_SKIP_PIXELS", 19 );
    lua_rawseti( L, -2, 159 );
    lua_pushlstring( L, "GL_PACK_SKIP_ROWS", 17 );
    lua_rawseti( L, -2, 160 );
    lua_pushlstring( L, "GL_PACK_SWAP_BYTES", 18 );
    lua_rawseti( L, -2, 161 );
    lua_pushlstring( L, "GL_PERSPECTIVE_CORRECTION_HINT", 30 );
    lua_rawseti( L, -2, 162 );
    lua_pushlstring( L, "GL_PIXEL_MAP_A_TO_A_SIZE", 24 );
    lua_rawseti( L, -2, 163 );
    lua_pushlstring( L, "GL_PIXEL_MAP_B_TO_B_SIZE", 24 );
    lua_rawseti( L, -2, 164 );
    lua_pushlstring( L, "GL_PIXEL_MAP_G_TO_G_SIZE", 24 );
    lua_rawseti( L, -2, 165 );
    lua_pushlstring( L, "GL_PIXEL_MAP_I_TO_A_SIZE", 24 );
    lua_rawseti( L, -2, 166 );
    lua_pushlstring( L, "GL_PIXEL_MAP_I_TO_B_SIZE", 24 );
    lua_rawseti( L, -2, 167 );
    lua_pushlstring( L, "GL_PIXEL_MAP_I_TO_G_SIZE", 24 );
    lua_rawseti( L, -2, 168 );
    lua_pushlstring( L, "GL_PIXEL_MAP_I_TO_I_SIZE", 24 );
    lua_rawseti( L, -2, 169 );
    lua_pushlstring( L, "GL_PIXEL_MAP_I_TO_R_SIZE", 24 );
    lua_rawseti( L, -2, 170 );
    lua_pushlstring( L, "GL_PIXEL_MAP_R_TO_R_SIZE", 24 );
    lua_rawseti( L, -2, 171 );
    lua_pushlstring( L, "GL_PIXEL_MAP_S_TO_S_SIZE", 24 );
    lua_rawseti( L, -2, 172 );
    lua_pushlstring( L, "GL_POINT_SIZE", 13 );
    lua_rawseti( L, -2, 173 );
    lua_pushlstring( L, "GL_POINT_SIZE_GRANULARITY", 25 );
    lua_rawseti( L, -2, 174 );
    lua_pushlstring( L, "GL_POINT_SIZE_RANGE", 19 );
    lua_rawseti( L, -2, 175 );
    lua_pushlstring( L, "GL_POINT_SMOOTH", 15 );
    lua_rawseti( L, -2, 176 );
    lua_pushlstring( L, "GL_POINT_SMOOTH_HINT", 20 );
    lua_rawseti( L, -2, 177 );
    lua_pushlstring( L, "GL_POLYGON_MODE", 15 );
    lua_rawseti( L, -2, 178 );
    lua_pushlstring( L, "GL_POLYGON_OFFSET_FACTOR", 24 );
    lua_rawseti( L, -2, 179 );
    lua_pushlstring( L, "GL_POLYGON_OFFSET_UNITS", 23 );
    lua_rawseti( L, -2, 180 );
    lua_pushlstring( L, "GL_POLYGON_OFFSET_FILL", 22 );
    lua_rawseti( L, -2, 181 );
    lua_pushlstring( L, "GL_POLYGON_OFFSET_LINE", 22 );
    lua_rawseti( L, -2, 182 );
    lua_pushlstring( L, "GL_POLYGON_OFFSET_POINT", 23 );
    lua_rawseti( L, -2, 183 );
    lua_pushlstring( L, "GL_POLYGON_SMOOTH", 17 );
    lua_rawseti( L, -2, 184 );
    lua_pushlstring( L, "GL_POLYGON_SMOOTH_HINT", 22 );
    lua_rawseti( L, -2, 185 );
    lua_pushlstring( L, "GL_POLYGON_STIPPLE", 18 );
    lua_rawseti( L, -2, 186 );
    lua_pushlstring( L, "GL_PROJECTION_MATRIX", 20 );
    lua_rawseti( L, -2, 187 );
    lua_pushlstring( L, "GL_PROJECTION_STACK_DEPTH", 25 );
    lua_rawseti( L, -2, 188 );
    lua_pushlstring( L, "GL_READ_BUFFER", 14 );
    lua_rawseti( L, -2, 189 );
    lua_pushlstring( L, "GL_RED_BIAS", 11 );
    lua_rawseti( L, -2, 190 );
    lua_pushlstring( L, "GL_RED_BITS", 11 );
    lua_rawseti( L, -2, 191 );
    lua_pushlstring( L, "GL_RED_SCALE", 12 );
    lua_rawseti( L, -2, 192 );
    lua_pushlstring( L, "GL_RENDER_MODE", 14 );
    lua_rawseti( L, -2, 193 );
    lua_pushlstring( L, "GL_RGBA_MODE", 12 );
    lua_rawseti( L, -2, 194 );
    lua_pushlstring( L, "GL_SCISSOR_BOX", 14 );
    lua_rawseti( L, -2, 195 );
    lua_pushlstring( L, "GL_SCISSOR_TEST", 15 );
    lua_rawseti( L, -2, 196 );
    lua_pushlstring( L, "GL_SHADE_MODEL", 14 );
    lua_rawseti( L, -2, 197 );
    lua_pushlstring( L, "GL_STENCIL_BITS", 15 );
    lua_rawseti( L, -2, 198 );
    lua_pushlstring( L, "GL_STENCIL_CLEAR_VALUE", 22 );
    lua_rawseti( L, -2, 199 );
    lua_pushlstring( L, "GL_STENCIL_FAIL", 15 );
    lua_rawseti( L, -2, 200 );
    lua_pushlstring( L, "GL_STENCIL_FUNC", 15 );
    lua_rawseti( L, -2, 201 );
    lua_pushlstring( L, "GL_STENCIL_PASS_DEPTH_FAIL", 26 );
    lua_rawseti( L, -2, 202 );
    lua_pushlstring( L, "GL_STENCIL_PASS_DEPTH_PASS", 26 );
    lua_rawseti( L, -2, 203 );
    lua_pushlstring( L, "GL_STENCIL_REF", 14 );
    lua_rawseti( L, -2, 204 );
    lua_pushlstring( L, "GL_STENCIL_TEST", 15 );
    lua_rawseti( L, -2, 205 );
    lua_pushlstring( L, "GL_STENCIL_VALUE_MASK", 21 );
    lua_rawseti( L, -2, 206 );
    lua_pushlstring( L, "GL_STENCIL_WRITEMASK", 20 );
    lua_rawseti( L, -2, 207 );
    lua_pushlstring( L, "GL_STEREO", 9 );
    lua_rawseti( L, -2, 208 );
    lua_pushlstring( L, "GL_SUBPIXEL_BITS", 16 );
    lua_rawseti( L, -2, 209 );
    lua_pushlstring( L, "GL_TEXTURE_1D", 13 );
    lua_rawseti( L, -2, 210 );
    lua_pushlstring( L, "GL_TEXTURE_2D", 13 );
    lua_rawseti( L, -2, 211 );
    lua_pushlstring( L, "GL_TEXTURE_COORD_ARRAY", 22 );
    lua_rawseti( L, -2, 212 );
    lua_pushlstring( L, "GL_TEXTURE_COORD_ARRAY_SIZE", 27 );
    lua_rawseti( L, -2, 213 );
    lua_pushlstring( L, "GL_TEXTURE_COORD_ARRAY_STRIDE", 29 );
    lua_rawseti( L, -2, 214 );
    lua_pushlstring( L, "GL_TEXTURE_COORD_ARRAY_TYPE", 27 );
    lua_rawseti( L, -2, 215 );
    lua_pushlstring( L, "GL_TEXTURE_ENV_COLOR", 20 );
    lua_rawseti( L, -2, 216 );
    lua_pushlstring( L, "GL_TEXTURE_ENV_MODE", 19 );
    lua_rawseti( L, -2, 217 );
    lua_pushlstring( L, "GL_TEXTURE_GEN_Q", 16 );
    lua_rawseti( L, -2, 218 );
    lua_pushlstring( L, "GL_TEXTURE_GEN_R", 16 );
    lua_rawseti( L, -2, 219 );
    lua_pushlstring( L, "GL_TEXTURE_GEN_S", 16 );
    lua_rawseti( L, -2, 220 );
    lua_pushlstring( L, "GL_TEXTURE_GEN_T", 16 );
    lua_rawseti( L, -2, 221 );
    lua_pushlstring( L, "GL_TEXTURE_MATRIX", 17 );
    lua_rawseti( L, -2, 222 );
    lua_pushlstring( L, "GL_TEXTURE_STACK_DEPTH", 22 );
    lua_rawseti( L, -2, 223 );
    lua_pushlstring( L, "GL_UNPACK_ALIGNMENT", 19 );
    lua_rawseti( L, -2, 224 );
    lua_pushlstring( L, "GL_UNPACK_ROW_LENGTH", 20 );
    lua_rawseti( L, -2, 225 );
    lua_pushlstring( L, "GL_UNPACK_SKIP_PIXELS", 21 );
    lua_rawseti( L, -2, 226 );
    lua_pushlstring( L, "GL_UNPACK_SWAP_BYTES", 20 );
    lua_rawseti( L, -2, 227 );
    lua_pushlstring( L, "GL_VERTEX_ARRAY", 15 );
    lua_rawseti( L, -2, 228 );
    lua_pushlstring( L, "GL_VERTEX_ARRAY_SIZE", 20 );
    lua_rawseti( L, -2, 229 );
    lua_pushlstring( L, "GL_VERTEX_ARRAY_STRIDE", 22 );
    lua_rawseti( L, -2, 230 );
    lua_pushlstring( L, "GL_VERTEX_ARRAY_TYPE", 20 );
    lua_rawseti( L, -2, 231 );
    lua_pushlstring( L, "GL_VIEWPORT", 11 );
    lua_rawseti( L, -2, 232 );
    lua_pushlstring( L, "GL_ZOOM_X", 9 );
    lua_rawseti( L, -2, 233 );
    lua_pushlstring( L, "GL_ZOOM_Y", 9 );
    lua_rawseti( L, -2, 234 );
    return 1;
}

static LUA_DECLARE( getCapabilityNames )
{
    lua_createtable( L, 60, 0 );
    lua_pushlstring( L, "GL_ALPHA_TEST", 13 );
    lua_rawseti( L, -2, 1 );
    lua_pushlstring( L, "GL_AUTO_NORMAL", 14 );
    lua_rawseti( L, -2, 2 );
    lua_pushlstring( L, "GL_BLEND", 8 );
    lua_rawseti( L, -2, 3 );
    lua_pushlstring( L, "GL_CLIP_PLANE0", 14 );
    lua_rawseti( L, -2, 4 );
    lua_pushlstring( L, "GL_CLIP_PLANE1", 14 );
    lua_rawseti( L, -2, 5 );
    lua_pushlstring( L, "GL_CLIP_PLANE2", 14 );
    lua_rawseti( L, -2, 6 );
    lua_pushlstring( L, "GL_CLIP_PLANE3", 14 );
    lua_rawseti( L, -2, 7 );
    lua_pushlstring( L, "GL_CLIP_PLANE4", 14 );
    lua_rawseti( L, -2, 8 );
    lua_pushlstring( L, "GL_CLIP_PLANE5", 14 );
    lua_rawseti( L, -2, 9 );
    lua_pushlstring( L, "GL_COLOR_LOGIC_OP", 17 );
    lua_rawseti( L, -2, 10 );
    lua_pushlstring( L, "GL_COLOR_MATERIAL", 17 );
    lua_rawseti( L, -2, 11 );
    lua_pushlstring( L, "GL_CULL_FACE", 12 );
    lua_rawseti( L, -2, 12 );
    lua_pushlstring( L, "GL_DEPTH_TEST", 13 );
    lua_rawseti( L, -2, 13 );
    lua_pushlstring( L, "GL_DITHER", 9 );
    lua_rawseti( L, -2, 14 );
    lua_pushlstring( L, "GL_FOG", 6 );
    lua_rawseti( L, -2, 15 );
    lua_pushlstring( L, "GL_INDEX_LOGIC_OP", 17 );
    lua_rawseti( L, -2, 16 );
    lua_pushlstring( L, "GL_LIGHT0", 9 );
    lua_rawseti( L, -2, 17 );
    lua_pushlstring( L, "GL_LIGHT1", 9 );
    lua_rawseti( L, -2, 18 );
    lua_pushlstring( L, "GL_LIGHT2", 9 );
    lua_rawseti( L, -2, 19 );
    lua_pushlstring( L, "GL_LIGHT3", 9 );
    lua_rawseti( L, -2, 20 );
    lua_pushlstring( L, "GL_LIGHT4", 9 );
    lua_rawseti( L, -2, 21 );
    lua_pushlstring( L, "GL_LIGHT5", 9 );
    lua_rawseti( L, -2, 22 );
    lua_pushlstring( L, "GL_LIGHT6", 9 );
    lua_rawseti( L, -2, 23 );
    lua_pushlstring( L, "GL_LIGHT7", 9 );
    lua_rawseti( L, -2, 24 );
    lua_pushlstring( L, "GL_LINE_STIPPLE", 15 );
    lua_rawseti( L, -2, 25 );
    lua_pushlstring( L, "GL_LOGIC_OP", 11 );
    lua_rawseti( L, -2, 26 );
    lua_pushlstring( L, "GL_MAP1_COLOR_4", 15 );
    lua_rawseti( L, -2, 27 );
    lua_pushlstring( L, "GL_MAP1_INDEX", 13 );
    lua_rawseti( L, -2, 28 );
    lua_pushlstring( L, "GL_MAP1_NORMAL", 14 );
    lua_rawseti( L, -2, 29 );
    lua_pushlstring( L, "GL_MAP1_TEXTURE_COORD_1", 23 );
    lua_rawseti( L, -2, 30 );
    lua_pushlstring( L, "GL_MAP1_TEXTURE_COORD_2", 23 );
    lua_rawseti( L, -2, 31 );
    lua_pushlstring( L, "GL_MAP1_TEXTURE_COORD_3", 23 );
    lua_rawseti( L, -2, 32 );
    lua_pushlstring( L, "GL_MAP1_TEXTURE_COORD_4", 23 );
    lua_rawseti( L, -2, 33 );
    lua_pushlstring( L, "GL_MAP1_VERTEX_3", 16 );
    lua_rawseti( L, -2, 34 );
    lua_pushlstring( L, "GL_MAP1_VERTEX_4", 16 );
    lua_rawseti( L, -2, 35 );
    lua_pushlstring( L, "GL_MAP2_COLOR_4", 15 );
    lua_rawseti( L, -2, 36 );
    lua_pushlstring( L, "GL_MAP2_INDEX", 13 );
    lua_rawseti( L, -2, 37 );
    lua_pushlstring( L, "GL_MAP2_NORMAL", 14 );
    lua_rawseti( L, -2, 38 );
    lua_pushlstring( L, "GL_MAP2_TEXTURE_COORD_1", 23 );
    lua_rawseti( L, -2, 39 );
    lua_pushlstring( L, "GL_MAP2_TEXTURE_COORD_2", 23 );
    lua_rawseti( L, -2, 40 );
    lua_pushlstring( L, "GL_MAP2_TEXTURE_COORD_3", 23 );
    lua_rawseti( L, -2, 41 );
    lua_pushlstring( L, "GL_MAP2_TEXTURE_COORD_4", 23 );
    lua_rawseti( L, -2, 42 );
    lua_pushlstring( L, "GL_MAP2_VERTEX_3", 16 );
    lua_rawseti( L, -2, 43 );
    lua_pushlstring( L, "GL_MAP2_VERTEX_4", 16 );
    lua_rawseti( L, -2, 44 );
    lua_pushlstring( L, "GL_NORMALIZE", 12 );
    lua_rawseti( L, -2, 45 );
    lua_pushlstring( L, "GL_POINT_SMOOTH", 15 );
    lua_rawseti( L, -2, 46 );
    lua_pushlstring( L, "GL_POLYGON_OFFSET_FILL", 22 );
    lua_rawseti( L, -2, 47 );
    lua_pushlstring( L, "GL_POLYGON_OFFSET_LINE", 22 );
    lua_rawseti( L, -2, 48 );
    lua_pushlstring( L, "GL_POLYGON_OFFSET_POINT", 23 );
    lua_rawseti( L, -2, 49 );
    lua_pushlstring( L, "GL_POLYGON_SMOOTH", 17 );
    lua_rawseti( L, -2, 50 );
    lua_pushlstring( L, "GL_POLYGON_STIPPLE", 18 );
    lua_rawseti( L, -2, 51 );
    lua_pushlstring( L, "GL_SCISSOR_TEST", 15 );
    lua_rawseti( L, -2, 52 );
    lua_pushlstring( L, "GL_STENCIL_TEST", 15 );
    lua_rawseti( L, -2, 53 );
    lua_pushlstring( L, "GL_TEXTURE_1D", 13 );
    lua_rawseti( L, -2, 54 );
    lua_pushlstring( L, "GL_TEXTURE_2D", 13 );
    lua_rawseti( L, -2, 55 );
    lua_pushlstring( L, "GL_TEXTURE_GEN_Q", 16 );
    lua_rawseti( L, -2, 56 );
    lua_pushlstring( L, "GL_TEXTURE_GEN_R", 16 );
    lua_rawseti( L, -2, 57 );
    lua_pushlstring( L, "GL_TEXTURE_GEN_S", 16 );
    lua_rawseti( L, -2, 58 );
    lua_pushlstring( L, "GL_TEXTURE_GEN_T", 16 );
    lua_rawseti( L, -2, 59 );
    return 1;
}

static LUA_DECLARE( intToColor )
{
    unsigned int color;

    LUA_ARGS_BEGIN;
    argStream.ReadNumber( color );
    LUA_ARGS_END;

    RwColor rwcolor = color;

    lua_pushnumber( L, (double)rwcolor.r / 255.0f );
    lua_pushnumber( L, (double)rwcolor.g / 255.0f );
    lua_pushnumber( L, (double)rwcolor.b / 255.0f );
    lua_pushnumber( L, (double)rwcolor.a / 255.0f );
    return 4;
}

static const luaL_Reg gl_interface[] =
{
    LUA_METHOD( create ),
    LUA_METHOD( getParamNames ),
    LUA_METHOD( getCapabilityNames ),
    LUA_METHOD( intToColor ),
    { NULL, NULL }
};

void luagl_open( lua_State *L )
{
    // Only initialize OpenGL if it is available on this system.
    if ( glMainLibrary )
    {
        luaL_openlib( L, "gl", gl_interface, 0 );
        lua_pop( L, 1 );
    }
}